import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { BottomNavbar, Sidebar } from "@/app/components/sidebar"
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className="  min-h-screen sm:grid grid-cols-12">
					<div className="sm:col-span-2">
						<Sidebar />
					</div>
					<div className="col-span-10 container p-2">{children}</div>
					<BottomNavbar />
					<Toaster />
				</main>
			</body>
		</html>
	)
}
